import { ExecutionPlan } from "@/planning";

export class SqlGenerator {
  generate(plan: ExecutionPlan): {
    migration: string;
    rollback: string;
  } {
    const migration: string[] = [];
    const rollback: string[] = [];

    migration.push("-- ==================================");
    migration.push("-- Generated by LineageGuard");
    migration.push("-- Review before execution");
    migration.push("-- ==================================");
    migration.push("");

    rollback.push("-- ==================================");
    rollback.push("-- Rollback Script");
    rollback.push("-- ==================================");
    rollback.push("");

    for (const change of plan.requiredChanges) {
      switch (change.type) {
        case "rename_column":
          migration.push(`-- ${change.description}`);
          migration.push("-- ALTER TABLE ...");
          migration.push("");

          rollback.push(`-- Undo: ${change.description}`);
          rollback.push("-- ALTER TABLE ...");
          rollback.push("");
          break;

        case "drop_column":
          migration.push(`-- ${change.description}`);
          migration.push("-- ALTER TABLE ...");
          migration.push("");

          rollback.push(
            "-- Manual rollback required."
          );
          rollback.push("");
          break;

        default:
          migration.push(`-- ${change.description}`);
          migration.push("");
      }
    }

    return {
      migration: migration.join("\n"),
      rollback: rollback.join("\n"),
    };
  }
}