import { z } from "zod";

/**
 * Overall impact severity.
 */
export const ImpactLevelSchema = z.enum([
  "LOW",
  "MEDIUM",
  "HIGH",
  "CRITICAL",
]);

export type ImpactLevel = z.infer<
  typeof ImpactLevelSchema
>;

/**
 * Recommendation generated by the Impact Engine.
 */
export const RecommendationSchema = z.object({
  id: z.string(),

  title: z.string(),

  description: z.string(),

  required: z.boolean(),
});

export type Recommendation = z.infer<
  typeof RecommendationSchema
>;

/**
 * Asset affected by the proposed schema change.
 */
export const ImpactedAssetSchema = z.object({
  urn: z.string(),

  name: z.string(),

  type: z.enum([
    "DATASET",
    "DASHBOARD",
    "CHART",
    "PIPELINE",
    "JOB",
  ]),
});

export type ImpactedAsset = z.infer<
  typeof ImpactedAssetSchema
>;

/**
 * Final report written back into DataHub.
 */
export const ImpactReportSchema = z.object({
  summary: z.string(),

  score: z.number().min(0).max(100),

  level: ImpactLevelSchema,

  requiresApproval: z.boolean(),

  affectedColumns: z.array(z.string()),

  affectedAssets: z.array(
    ImpactedAssetSchema
  ),

  recommendations: z.array(
    RecommendationSchema
  ),

  triggeredRules: z.array(z.object({
    id: z.string(),
    description: z.string(),
    weight: z.number(),
  })).optional(),

  generatedAt: z.string(),

  approvedAt: z.string().optional(),

  metadata: z.object({
    generatedBy: z.literal("LineageGuard"),

    version: z.string(),
  }),
});

export type ImpactReport = z.infer<
  typeof ImpactReportSchema
>;