import { ExecutionPlan } from '../planner/types.js';
import { RiskAssessment } from '../risk/types.js';
import { ContextBundle } from '../context/type.js';

import { DocumentationArtifact } from './types.js';

export class DocumentationGenerator {
  generate(
    plan: ExecutionPlan,
    risk: RiskAssessment,
    context?: ContextBundle
  ): DocumentationArtifact {
    // Determine operation type from required changes
    const operationType = plan.requiredChanges?.[0]?.type || 'unknown';
    const datasetName = context?.dataset?.name || plan.affectedDataset || 'unknown';
    const platform = context?.dataset?.platform || 'unknown';
    const generatedAt = new Date().toISOString();
    const runId = this.generateRunId(plan);

    const markdown = [
      '# LineageGuard Change Report',
      '',
      '## Change Summary',
      '',
      '| Field | Value |',
      '|---|---|',
      `| Dataset | \`${datasetName}\` |`,
      `| Platform | \`${platform}\` |`,
      `| Operation | \`${operationType}\` |`,
      `| Risk | \`${risk.overallRisk}\` |`,
      `| Risk Score | \`${risk.score}/100\` |`,
      `| Approval | \`${risk.requiresApproval ? 'Required' : 'Not Required'}\` |`,
      `| Status | \`PENDING\` |`,
      '',
      '## Requested Change',
      '',
      plan.summary || plan.intent || 'Schema change request',
      '',
      '## Affected Columns',
      '',
      ...(plan.affectedColumns?.map(col => `- \`${col}\```) || ['No columns affected']),
      '',
      '## Execution Plan',
      '',
      plan.intent || 'Schema modification based on the requested change',
      '',
      '## Risk Assessment',
      '',
      `**Level:** \`${risk.overallRisk}\``,
      `**Score:** \`${risk.score}/100\``,
      '',
      '### Findings',
      '',
      ...(risk.findings?.map(f => `- ${f.category}: ${f.message}`) || ['No specific findings detected']),
      '',
      '### Recommendations',
      '',
      ...(risk.recommendations?.map(r => `- ${r}`) || ['No specific recommendations']),
      '',
      '## Impact Analysis',
      '',
      '### Affected Assets',
      '',
      ...(plan.affectedColumns?.map(col => `- \`${datasetName}\` (affected column: \`${col}\`)`) || ['No specific assets detected']),
      '',
      '> No downstream assets were detected in the available DataHub lineage context.',
      '',
      '## Approval',
      '',
      `**Status:** \`PENDING\``,
      '',
      `**Reason:** Change requires approval before execution`,
      '',
      '## Migration',
      '',
      'The following validated migration will be applied:',
      '',
      '```sql',
      '<See migration.sql for the validated DDL>',
      '```',
      '',
      '## Rollback',
      '',
      '<See ROLLBACK.sql for rollback strategy>',
      '',
      '## LineageGuard Metadata',
      '',
      `* Generated by: \`LineageGuard\``,
      `* Version: \`1.0.0\``,
      `* Generated at: \`${generatedAt}\``,
      `* Run ID: \`${runId}\``,
    ].join('\n');

    return {
      markdown,
    };
  }

  private generateRunId(plan: ExecutionPlan): string {
    const hash = JSON.stringify({
      intent: plan.intent,
      affectedColumns: plan.affectedColumns,
      timestamp: Date.now(),
    });
    return hash.substring(0, 8).replace(/[^a-zA-Z0-9]/g, '');
  }
}
