import { ExecutionPlan } from "../planner/types.js";
import { RiskAssessment } from "../risk/types.js";
import { logger } from "../config/logger.js";

import { PrismaGenerator } from "./prisma.js";
import { SQLGenerator } from "./sql.js";
import { RollbackGenerator } from "./rollback.js";
import { DocumentationGenerator } from "./documentation.js";
import { DbtGenerator } from "./db.js";
import { GenerationValidator } from "./validator.js";
import { GenerationResult } from "./types.js";

export class Generator {

  constructor(

    private readonly prisma: PrismaGenerator,

    private readonly sql = new SQLGenerator(),

    private readonly rollback =
      new RollbackGenerator(),

    private readonly documentation =
      new DocumentationGenerator(),

    private readonly dbt =
      new DbtGenerator(),

    private readonly validator =
      new GenerationValidator()

  ) {}

  async generate(

    originalSchema: string,

    plan: ExecutionPlan,

    risk: RiskAssessment

  ): Promise<GenerationResult> {

    // Validate input schema
    if (!originalSchema || originalSchema.trim().length === 0) {
      logger.warn({
        event: "generator_empty_schema_received",
        schemaLength: originalSchema?.length || 0,
      }, "Generator received empty schema - this indicates an issue with schema collection");
    } else {
      logger.info({
        event: "generator_schema_received",
        schemaLength: originalSchema.length,
        schemaPreview: originalSchema.substring(0, 200),
      }, "Generator received schema for processing");
    }

    // Step 1
    const prismaResult =
      await this.prisma.generate(
        originalSchema,
        plan
      );

    // Step 2 - Generate SQL from the migration
    let migrationSql = prismaResult.migration || "";
    
    if (!migrationSql || migrationSql.trim().length === 0) {
      logger.warn({
        event: "generator_no_migration_from_prisma",
        hasMigration: !!prismaResult.migration,
      }, "No migration generated by PrismaGenerator - SQL generation will be empty");
      migrationSql = "-- No migration generated";
    }
    
    const sql =
      this.sql.generate(migrationSql);

    logger.info({
      event: "generator_sql_generated",
      sqlLength: sql.migration.length,
    }, "✓ SQL Generated");

    // Step 3
    const rollback =
      this.rollback.generate(
        plan
      );

    logger.info({ event: "generator_rollback_generated" }, "✓ Rollback Generated");

    // Step 4
    const documentation =
      this.documentation.generate(
        plan,
        risk
      );

    logger.info({ event: "generator_documentation_generated" }, "✓ Documentation Generated");

    // Step 5
    const dbt =
      this.dbt.generate(
        plan
      );

    return this.validator.validate({

      prisma: prismaResult,

      sql,

      rollback,

      documentation,

      dbt

    });

  }

}