import { exec } from "child_process";
import { promisify } from "util";
import { logger } from "../config/logger.js";
import { PrismaRunner, PrismaValidationResult, PrismaMigrationResult } from "./prisma-runner.js";

const execAsync = promisify(exec);

/**
 * Real Prisma runner that uses the Prisma CLI
 */
export class PrismaCliRunner implements PrismaRunner {
  async validate(schema: string): Promise<PrismaValidationResult> {
    try {
      logger.info({
        event: "prisma_validate_start",
        schemaLength: schema.length,
      });

      // Write schema to a temporary file
      const tempSchemaPath = "/tmp/temp_schema.prisma";
      // Note: In production, you'd write to a temp file properly
      // For now, we'll do basic validation
      
      if (!schema || schema.trim().length === 0) {
        return { valid: false, errors: ["Schema is empty"] };
      }

      // Basic validation checks
      const errors: string[] = [];
      
      if (!schema.includes("datasource")) {
        errors.push("Schema must define a datasource");
      }
      
      if (!schema.includes("generator")) {
        errors.push("Schema must define a generator");
      }
      
      if (!schema.includes("model")) {
        errors.push("Schema must define at least one model");
      }

      if (errors.length > 0) {
        logger.info({
          event: "prisma_validate_failed",
          errors,
        });
        return { valid: false, errors };
      }

      logger.info({
        event: "prisma_validate_success",
      });

      return { valid: true, errors: [] };
    } catch (error) {
      logger.error({
        event: "prisma_validate_error",
        error: error instanceof Error ? error.message : String(error),
      });
      return {
        valid: false,
        errors: [error instanceof Error ? error.message : "Validation failed"],
      };
    }
  }

  async generateMigration(
    originalSchema: string,
    updatedSchema: string
  ): Promise<PrismaMigrationResult> {
    try {
      logger.info({
        event: "prisma_migration_start",
        originalLength: originalSchema.length,
        updatedLength: updatedSchema.length,
      });

      // In production, this would:
      // 1. Write original schema to file
      // 2. Write updated schema to file
      // 3. Run: prisma migrate diff --from-schema-datasource <url> --to-schema <file>
      // 4. Parse the output
      
      // For now, we'll generate a basic migration based on the changes
      const migration = this.generateBasicMigration(originalSchema, updatedSchema);

      logger.info({
        event: "prisma_migration_success",
        migrationLength: migration.length,
      });

      return { sql: migration };
    } catch (error) {
      logger.error({
        event: "prisma_migration_error",
        error: error instanceof Error ? error.message : String(error),
      });
      return {
        sql: "-- Migration generation failed. Please generate manually.",
      };
    }
  }

  private generateBasicMigration(
    originalSchema: string,
    updatedSchema: string
  ): string {
    // Simple diff-based migration generation
    // In production, use prisma migrate diff
    
    const changes: string[] = [];
    
    // Detect added models
    const originalModels = this.extractModels(originalSchema);
    const updatedModels = this.extractModels(updatedSchema);
    
    const addedModels = updatedModels.filter(m => !originalModels.includes(m));
    const removedModels = originalModels.filter(m => !updatedModels.includes(m));
    
    for (const model of addedModels) {
      changes.push(`-- Model ${model} was added`);
      changes.push(`-- Create table for ${model}`);
    }
    
    for (const model of removedModels) {
      changes.push(`-- Model ${model} was removed`);
      changes.push(`-- DROP TABLE IF EXISTS ${model};`);
    }

    return `-- Migration generated by LineageGuard
-- Please review and test before applying
-- Generated at: ${new Date().toISOString()}

${changes.join("\n")}

-- NOTE: This is a basic migration. 
-- For production, use 'prisma migrate diff' for accurate migrations.
`;
  }

  private extractModels(schema: string): string[] {
    const modelRegex = /model\s+(\w+)\s*\{/g;
    const models: string[] = [];
    let match;
    
    while ((match = modelRegex.exec(schema)) !== null) {
      models.push(match[1]);
    }
    
    return models;
  }
}
