import { SQLArtifact } from './types.js';

export class SQLGenerator {
  generate(rawSql: string, platform?: string): SQLArtifact {
    // Note: We do NOT sanitize trusted DDL generated by our own deterministic engine.
    // Sanitization is only for user-provided SQL input to prevent injection.
    // Our DDLGenerator produces safe, validated SQL statements.

    const formatted = [
      '-- =====================================',
      '-- Generated by LineageGuard',
      platform ? `-- Platform: ${platform}` : '',
      '-- Review before applying',
      '-- =====================================',
      '',
      rawSql.trim(),
      '',
    ]
      .filter((line) => line !== '')
      .join('\n');

    return {
      migration: rawSql.trim(),
      formatted,
      platform,
    };
  }
}
