import { SQLArtifact } from "./types";

export class SQLGenerator {
  generate(rawSql: string): SQLArtifact {
    const formatted = [
      "-- =====================================",
      "-- Generated by LineageGuard",
      "-- Review before applying",
      "-- =====================================",
      "",
      rawSql.trim(),
      "",
    ].join("\n");

    return {
      migration: rawSql,
      formatted,
    };
  }
}