import { SQLArtifact } from "./types";
import { sanitizeSQL } from "../utils/security.js";

export class SQLGenerator {
  generate(rawSql: string): SQLArtifact {
    // Sanitize SQL to prevent injection
    const sanitizedSql = sanitizeSQL(rawSql);

    const formatted = [
      "-- =====================================",
      "-- Generated by LineageGuard",
      "-- Review before applying",
      "-- =====================================",
      "",
      sanitizedSql.trim(),
      "",
    ].join("\n");

    return {
      migration: sanitizedSql,
      formatted,
    };
  }
}