import { z } from "zod";

/**
 * Updated Prisma schema after applying the requested change.
 */
export const PrismaArtifactSchema = z.object({
  schema: z.string().min(1),

  valid: z.boolean(),
});

export type PrismaArtifact = z.infer<
  typeof PrismaArtifactSchema
>;

/**
 * SQL generated by Prisma.
 */
export const SQLArtifactSchema = z.object({
  migration: z.string(),

  formatted: z.string(),
});

export type SQLArtifact = z.infer<
  typeof SQLArtifactSchema
>;

/**
 * Rollback instructions.
 */
export const RollbackArtifactSchema = z.object({
  sql: z.string(),

  automatic: z.boolean(),
});

export type RollbackArtifact = z.infer<
  typeof RollbackArtifactSchema
>;

/**
 * Markdown documentation.
 */
export const DocumentationArtifactSchema =
  z.object({
    markdown: z.string(),
  });

export type DocumentationArtifact =
  z.infer<typeof DocumentationArtifactSchema>;

/**
 * Optional dbt changes.
 */
export const DbtArtifactSchema = z.object({
  files: z.array(z.string()),
});

export type DbtArtifact = z.infer<
  typeof DbtArtifactSchema
>;

/**
 * Final output of the Code Generation Engine.
 */
export const GenerationResultSchema = z.object({
  prisma: PrismaArtifactSchema,

  sql: SQLArtifactSchema,

  rollback: RollbackArtifactSchema,

  documentation:
    DocumentationArtifactSchema,

  dbt: DbtArtifactSchema.optional(),
});

export type GenerationResult = z.infer<
  typeof GenerationResultSchema
>;