import { config } from "../config/config.js";

import { ContextEngine } from "../context/context-engine.js";
import { PlanningEngine } from "../planner/planning-engine.js";
import { RiskEngine } from "../risk/risk-engine.js";
import { Generator } from "../generators/generator.js";
import { ImpactEngine } from "../impact/impact-engine.js";
import { ApprovalEngine } from "../approval/approval-engine.js";
import { OctokitGitHubClient } from "../github/octokit-client.js";
import { GitHubEngine } from "../github/github-engine.js";
import { Orchestrator } from "../orchestration/orchestrator.js";
import { AnthropicClient } from "../llm/anthropic.js";
import { MCPTransport } from "../mcp/transport.js";
import { MCPClient } from "../mcp/client.js";
import { DataHubClient } from "../mcp/datahub-client.js";
import { PrismaGenerator } from "../generators/prisma.js";
import { Planner, LLMClient } from "../planner/planner.js";
import { LLMEditor } from "../generators/llm-editor.js";
import { PrismaRunner, PrismaValidationResult, PrismaMigrationResult } from "../generators/prisma-runner.js";
import { MetadataWriter } from "../impact/metadata-writer.js";
import { ContextStage, PlanningStage, RiskStage, GeneratorStage, ImpactStage, ApprovalStage, GitHubStage } from "../orchestration/stages/index.js";

/**
 * Composition Root
 *
 * Every dependency in the application
 * is created here exactly once.
 */

export class ApplicationContainer {

  readonly context: ContextEngine;

  readonly planning: PlanningEngine;

  readonly risk: RiskEngine;

  readonly generator: Generator;

  readonly impact: ImpactEngine;

  readonly approval: ApprovalEngine;

  readonly github: GitHubEngine;

  readonly orchestrator: Orchestrator;

  constructor() {

    /**
     * Infrastructure
     */

    const mcpTransport = new MCPTransport({
      timeoutMs: 30000,
    });

    const mcpClient = new MCPClient(mcpTransport);

    const datahubClient = new DataHubClient(mcpClient);

    const anthropicClient = new AnthropicClient({
      apiKey: config.anthropic.apiKey,
      model: "claude-3-5-sonnet-20241022",
      maxTokens: 4096,
      temperature: 0,
    });

    const githubClient = new OctokitGitHubClient(
      config.github.token,
      config.github.owner,
      config.github.repository
    );

    /**
     * Generators
     */

    const llmEditor: LLMEditor = {
      editSchema: async (request) => {
        const response = await anthropicClient.message({
          system: "You are a database schema expert. Edit the Prisma schema according to the execution plan.",
          messages: [
            {
              role: "user",
              content: `Current schema:\n${request.schema}\n\nExecution plan:\n${JSON.stringify(request.plan, null, 2)}\n\nReturn the updated Prisma schema only.`,
            },
          ],
        });

        return {
          updatedSchema: response.content,
        };
      },
    };

    const prismaRunner: PrismaRunner = {
      validate: async (schema: string): Promise<PrismaValidationResult> => {
        // In production, this would run prisma validate
        // For now, we do basic schema validation
        if (!schema || schema.trim().length === 0) {
          return { valid: false, errors: ["Schema is empty"] };
        }
        
        // Check for basic Prisma schema structure
        if (!schema.includes("model") && !schema.includes("datasource")) {
          return { valid: false, errors: ["Schema must contain at least one model or datasource"] };
        }
        
        return { valid: true, errors: [] };
      },
      generateMigration: async (originalSchema: string, updatedSchema: string): Promise<PrismaMigrationResult> => {
        // In production, this would run prisma migrate diff
        // For now, we generate a placeholder migration
        const migration = `-- Migration generated by LineageGuard
-- Original schema length: ${originalSchema.length}
-- Updated schema length: ${updatedSchema.length}
-- 
-- This is a placeholder migration. In production, this would be generated
-- by running: prisma migrate diff --from-schema-datasource <source> --to-schema <file>
-- 
-- Review and update this migration before applying.
`;
        return { sql: migration };
      },
    };

    const prismaGenerator = new PrismaGenerator(llmEditor, prismaRunner);

    /**
     * Engines
     */

    const llmClient: LLMClient = {
      generate: async (systemPrompt: string, userPrompt: string): Promise<string> => {
        const response = await anthropicClient.message({
          system: systemPrompt,
          messages: [{ role: "user", content: userPrompt }],
        });
        return response.content;
      },
    };

    const planner = new Planner(llmClient);

    const metadataWriter: MetadataWriter = {
      write: async (report) => {
        // In production, this would write to DataHub
        // For now, we log the impact report
        console.log("Writing impact report to DataHub:");
        console.log(`- Summary: ${report.summary}`);
        console.log(`- Score: ${report.score}`);
        console.log(`- Level: ${report.level}`);
        console.log(`- Affected Columns: ${report.affectedColumns.join(", ")}`);
        console.log(`- Affected Assets: ${report.affectedAssets.length}`);
        console.log(`- Recommendations: ${report.recommendations.length}`);
        
        // In production, this would call DataHub's API to write:
        // - Impact report as a structured property on the dataset
        // - Tags for governance
        // - Comments documenting the change
      },
    };

    this.context = new ContextEngine(datahubClient);

    this.planning = new PlanningEngine(planner);

    this.risk = new RiskEngine();

    this.generator = new Generator(prismaGenerator);

    this.impact = new ImpactEngine(metadataWriter);

    this.approval = new ApprovalEngine();

    this.github = new GitHubEngine(githubClient);

    /**
     * Application
     */

    const contextStage = new ContextStage(this.context);
    const planningStage = new PlanningStage(this.planning);
    const riskStage = new RiskStage(this.risk);
    const generatorStage = new GeneratorStage(this.generator);
    const impactStage = new ImpactStage(this.impact);
    const approvalStage = new ApprovalStage(this.approval, false);
    const githubStage = new GitHubStage(
      this.github,
      config.github.owner,
      config.github.repository,
      config.github.baseBranch
    );

    this.orchestrator = new Orchestrator(
      [
        contextStage,
        planningStage,
        riskStage,
        generatorStage,
        impactStage,
        approvalStage,
        githubStage,
      ],
      config.github.owner,
      config.github.repository,
      config.github.baseBranch
    );

  }

}

export const container = new ApplicationContainer();