import { config } from "../config/config.js";
import { logger } from "../config/logger.js";
import { PrismaPg } from "@prisma/adapter-pg";
import { ContextEngine } from "../context/context-engine.js";
import { PlanningEngine } from "../planner/planning-engine.js";
import { RiskEngine } from "../risk/risk-engine.js";
import { Generator } from "../generators/generator.js";
import { ImpactEngine } from "../impact/impact-engine.js";
import { ApprovalEngine } from "../approval/approval-engine.js";
import { GitHubClient } from "../github/github-client.js";
import { GitHubEngine } from "../github/github-engine.js";
import { Orchestrator } from "../orchestration/orchestrator.js";
import { MCPTransport } from "../mcp/transport.js";
import { MCPClient } from "../mcp/client.js";
import { DataHubClient } from "../mcp/datahub-client.js";
import { PrismaGenerator } from "../generators/prisma.js";
import { Planner, LLMClient } from "../planner/planner.js";
import { LLMEditor } from "../generators/llm-editor.js";
import { PrismaRunner, PrismaValidationResult, PrismaMigrationResult } from "../generators/prisma-runner.js";
import { MetadataWriter } from "../impact/metadata-writer.js";
import { ContextStage, PlanningStage, RiskStage, GeneratorStage, ImpactStage, ApprovalStage, GitHubStage } from "../orchestration/stages/index.js";
import { createContainer } from "./production-container.js";
import { IdempotencyService } from "../utils/idempotency.js";
import { PrismaClient } from "@prisma/client";

/**
 * Development Container
 *
 * Uses mock implementations for external dependencies.
 * Intended for development and testing only.
 * NEVER use in production.
 */

export class DevelopmentContainer {

  readonly context: ContextEngine;

  readonly planning: PlanningEngine;

  readonly risk: RiskEngine;

  readonly generator: Generator;

  readonly impact: ImpactEngine;

  readonly approval: ApprovalEngine;

  readonly github: GitHubEngine;

  readonly orchestrator: Orchestrator;

  constructor() {

    /**
     * Infrastructure
     */

    const mcpTransport = new MCPTransport({
      timeoutMs: 30000,
    });

    const mcpClient = new MCPClient(mcpTransport);

    const datahubClient = new DataHubClient(mcpClient);

    const githubClient: GitHubClient = {
      createPullRequest: async (request) => {
        // Mock implementation for testing
        return {
          number: Math.floor(Math.random() * 1000),
          url: `https://github.com/${request.owner}/${request.repository}/pull/${Math.floor(Math.random() * 1000)}`,
        };
      },
      addLabels: async (prNumber, labels) => {
        // Mock implementation
      },
      requestReviewers: async (prNumber, reviewers) => {
        // Mock implementation
      },
    };

    /**
     * Generators
     */

    const llmEditor: LLMEditor = {
      editSchema: async (request) => {
        // Mock implementation for testing - return a valid Prisma schema
        return {
          updatedSchema: `// This is an autogenerated Prisma schema
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model users {
  id        Int      @id @default(autoincrement())
  name      String
  email     String   @unique
  createdAt DateTime @default(now())
}`,
        };
      },
    };

    const prismaRunner: PrismaRunner = {
      validate: async (schema: string): Promise<PrismaValidationResult> => {
        // In production, this would run prisma validate
        // For now, we do basic schema validation
        if (!schema || schema.trim().length === 0) {
          return { valid: false, errors: ["Schema is empty"] };
        }
        
        // Check for basic Prisma schema structure
        if (!schema.includes("model") && !schema.includes("datasource")) {
          return { valid: false, errors: ["Schema must contain at least one model or datasource"] };
        }
        
        return { valid: true, errors: [] };
      },
      generateMigration: async (originalSchema: string, updatedSchema: string): Promise<PrismaMigrationResult> => {
        // In production, this would run prisma migrate diff
        // For now, we generate a placeholder migration
        const migration = `-- Migration generated by LineageGuard
-- Original schema length: ${originalSchema.length}
-- Updated schema length: ${updatedSchema.length}
-- 
-- This is a placeholder migration. In production, this would be generated
-- by running: prisma migrate diff --from-schema-datasource <source> --to-schema <file>
-- 
-- Review and update this migration before applying.
`;
        return { sql: migration };
      },
    };

    const prismaGenerator = new PrismaGenerator(llmEditor, prismaRunner);

    /**
     * Engines
     */

    const llmClient: LLMClient = {
      generate: async (systemPrompt: string, userPrompt: string): Promise<string> => {
        // Mock implementation for testing - return a mock execution plan
        return JSON.stringify({
          summary: "Add email column to users table",
          intent: "Add a new email column to the users table to store user email addresses",
          affectedDataset: "users",
          affectedColumns: ["email"],
          assumptions: [
            "The users table exists",
            "Email addresses should be required (not nullable)",
            "No existing data migration needed"
          ],
          missingInformation: [],
          requiredChanges: [
            {
              type: "add_column",
              description: "Add email column to users table",
            },
          ],
          confidence: 0.95,
          requiresApproval: false,
        });
      },
    };

    const planner = new Planner(llmClient);

    const metadataWriter: MetadataWriter = {
      write: async (report) => {
        // In production, this would write to DataHub
        // For now, we log the impact report
        logger.info({
          event: "datahub_write",
          summary: report.summary,
          score: report.score,
          level: report.level,
          affectedColumns: report.affectedColumns.join(", "),
          affectedAssets: report.affectedAssets.length,
          recommendations: report.recommendations.length,
        }, "Writing impact report to DataHub");

        // In production, this would call DataHub's API to write:
        // - Impact report as a structured property on the dataset
        // - Tags for governance
        // - Comments documenting the change
      },
    };

    this.context = new ContextEngine(datahubClient);

    this.planning = new PlanningEngine(planner);

    this.risk = new RiskEngine();

    this.generator = new Generator(prismaGenerator);

    this.impact = new ImpactEngine(metadataWriter);

    this.approval = new ApprovalEngine();

    this.github = new GitHubEngine(githubClient);

    /**
     * Idempotency - Mock implementation for development
     */
    // For development, we create a mock idempotency service that bypasses DB
    const mockIdempotencyService: IdempotencyService = {
      check: async () => ({
        isDuplicate: false,
        status: undefined,
        cachedResult: undefined,
      }),
      record: async () => undefined,
    } as any;

    /**
     * Application
     */

    const contextStage = new ContextStage(this.context, mockIdempotencyService);
    const planningStage = new PlanningStage(this.planning, mockIdempotencyService);
    const riskStage = new RiskStage(this.risk, mockIdempotencyService);
    const generatorStage = new GeneratorStage(this.generator, mockIdempotencyService);
    const impactStage = new ImpactStage(this.impact, mockIdempotencyService);
    const approvalStage = new ApprovalStage(this.approval, mockIdempotencyService, false);
    const githubStage = new GitHubStage(
      this.github,
      config.github.owner,
      config.github.repository,
      config.github.baseBranch,
      mockIdempotencyService
    );

    this.orchestrator = new Orchestrator(
      [
        contextStage,
        planningStage,
        riskStage,
        generatorStage,
        impactStage,
        approvalStage,
        githubStage,
      ],
      config.github.owner,
      config.github.repository,
      config.github.baseBranch,
      mockIdempotencyService
    );

  }

}

export const container = createContainer();